name: sos
description: "Document everything. Stay safe out there."
version: 3.0.2+24
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Flutter (Google)
  camera: ^0.12.0+1
  go_router: ^17.3.0
  intl: ^0.20.2
  path_provider: ^2.1.6
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2

  # Community
  after_layout: ^1.2.0
  permission_handler: ^12.0.3
  flutter_contacts: ^2.2.2
  gal: ^2.3.2
  geolocator: ^14.0.3
  provider: ^6.1.5+1
  share_plus: ^13.2.0

  # YWT
  ywt_private:
    path: ../ywt_private
  open_ui: 
    path: ../open_ui

dev_dependencies:
  dependency_validator: ^5.0.5
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.8

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/app-icon.png
    - assets/og-baddie.jpg

flutter_launcher_icons:
  image_path: assets/app-icon.png
  adaptive_icon_foreground: assets/app-icon.png
  adaptive_icon_background: "#A520DA"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter_native_splash:
  image: assets/app-icon.png
  image_dark: assets/app-icon.png
  color: "#A520DA"
  color_dark: "#A520DA"
  android: true
  ios: true
  web: false